application: portal-nodejs
version: 1
runtime: php55
api_version: 1
threadsafe: false

builtins:
- appstats: on
- deferred: on
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static
  application_readable: true


  # Serve php scripts.
- url: /(.+\.(php|html))$
  script: \1

- url: /
  script: index.php